default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prodigy_development

test:
  <<: *default
  database: prodigy_test

# without Docker

# production:
#   <<: *default
#   database: prodigy_production
#   username: prodigy
#   password: <%= ENV['PRODIGY_DATABASE_PASSWORD'] %>

production:
  <<: *default
  adapter: postgresql
  host: db
  username: postgres
  password: